### ISSUE TITLE
Need help clean up the data and transform json file into csv file

### ISSUE THREAD

**Issue by frankdou** [Wiredcraft/complexcity#1]
The project requires the help of the following points, perhaps is not enough,hope everyone could supplement.

1.Values like '\ u5ef6 \ u5b89' should converted to utf-8（can also do not have to do,cartodb seems to be automatically converted);

2.All json data need to transform into csv files, convenient classification of the query is displayed on the map,this is also cartodb require;

3.Need geographic information to each piece of information, however, most of the current data have this information, but need to keep the key of the correct and consistent;

**Comment by hunvreus** [comment]
Assigning to @zbal
